### ISSUE TITLE
`entropy_loss` 在训练过程中几乎不变，都是 -3.0 左右

### ISSUE THREAD

**Issue by cingtiye** [PaddlePaddle/Knover#101]
您好。请问 `entroy_loss` 训练过程中几乎不变，可能是哪个方面有问题？其他两个`loss`都会缓慢下降。
非常期待得到回复。
谢谢~

**Comment by sserdoubleh** [comment]
`entropy_loss`的最低值应该就是-3.0左右，均匀分布的时候`entropy_loss`最低，如果你在args里面加了`use_entropy=True`，那应该会维持这个情况，需要调整`entropy_loss`的系数才会，让其变化
