### ISSUE TITLE
关于中文多轮对话训练预料的构造

### ISSUE THREAD

**Issue by cingtiye** [PaddlePaddle/Knover#108]
您好！
        我想构造**多轮的训练预料**，比如我爬取了某个微博的所有评论，但是这些评论都是针对这个微博的不同的评论。类似这样的数据可以按照**时间顺序**作为多轮对话预料吗？还是说需要经过一些怎样的清洗和处理才可以？
非常期望得到您的回复~

**Comment by portia1026** [comment]
1）像这种社交媒体评论，通常是 Message Tree 结构，在语料构造时可以考虑保留这种结构信息，从一个节点到根节点作为一个多轮对话。如果直接按照时间顺序构造语料，句子间的连贯性可能会有问题。
2）关于语料进一步的清洗、处理，去掉一些低质的回复，通常也是需要的。
可以参考 [PLATO-XL ](https://arxiv.org/pdf/2109.09519.pdf) (Section 3.2) 和 [PLATO-2](https://aclanthology.org/2021.findings-acl.222.pdf) (Appendix A) 关于语料结构和语料清洗的介绍。
