### ISSUE TITLE
请问模型参数量怎么统计

### ISSUE THREAD

**Issue by guijuzhejiang** [PaddlePaddle/Knover#110]
如题，请问提供统计模型参数量的工具吗

**Comment by sserdoubleh** [comment]
静态图好像没有直接统计的一个函数，可以在 Knover 的 train script 里面创建完model 之后，像下面那样调用，得到总参数量
```
    import numpy as np
    total_params = 0
    for p in model.train_program.all_parameters():
        total_params += np.prod(p.shape)
    print("total params:", total_params)
```
一行的话，可以这么计算
```
    total_params = sum(map(lambda p: np.prod(p.shape), model.train_program.all_parameters()))
```

**Comment by guijuzhejiang** [comment]
感谢回复，我测试了第一种写法，计算的参数量为323.15M
同时使用下面api计算的参数量为607.1463M。
paddle.fluid.contrib.model_stat.summary(model.train_program)
请问这两种写法有什么不同吗？哪个是准确的？

**Comment by sserdoubleh** [comment]
可以根据模型配置估算一下哈，我这边的方法应该是准确的，那个一行的写法是有些问题，我更新了
方便的话可以说一下你的模型配置，可以对比一下
一般来说，标准的transformer结构可以这么估计参数：12 * L * D * D
L是网络层数，D是隐藏层大小，这里默认FFN的中间层维度是4D

**Comment by sserdoubleh** [comment]
看了下summary的问题，大概是它是根据op统计参数量的，但是统计op的类型有限，例如没有考虑embedding，另外如果像transformer复用参数的情况（如token_embedding也是最后分类层的weight），也有问题
https://github.com/PaddlePaddle/Paddle/blob/443cf71a2d4fe1e91547a58a70dd5d55bc449cbd/python/paddle/fluid/contrib/model_stat.py#L68

**Comment by guijuzhejiang** [comment]
感谢如此详细的回复，paddle.fluid.contrib.model_stat.summary应该是早期静态图参数量计算的bug。
用您提供的估算transformer参数方法，确实是300多M。
下面是模型配置，是24L默认的，我记得论文里面说24L的是310M参数，我的是323.15M，不知道这13M的偏差是出在哪里的
"hidden_size": 1024,
  "initializer_range": 0.02,
  "max_position_embeddings": 512,
  "latent_type_size": 20,
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "type_vocab_size": 2,
  "vocab_size": 32000

**Comment by sserdoubleh** [comment]
词表大小不同，8000->32000，大概 8M->32M
论文里的模型参数量也不是这么准确

**Comment by guijuzhejiang** [comment]
纳鲁好道，非常感谢，问题关闭
