### ISSUE TITLE
Low download speeds for the pretrained models

### ISSUE THREAD

**Issue by bakszero** [PaddlePaddle/Knover#12]
Hi, first of all, thanks for the really nice work!
I'm facing very low download speeds for the 24L model -- close to 20-30 KB/s using `wget`. Could you please help with an alternative mirror link? Thanks!

**Comment by portia1026** [comment]
> Hi, first of all, thanks for the really nice work!
> I'm facing very low download speeds for the 24L model -- close to 20-30 KB/s using `wget`. Could you please help with an alternative mirror link? Thanks!

Thanks for your interests on our work. Currently, I am not sure whether this low speed happens occasionally. We have several researchers downloaded the models from different countries and regions. Their reported download speeds range from 500kb/s to 4M/s. Maybe try to switch the network if possible? If this problem persists, please let us know.

**Comment by bakszero** [comment]
Sweet, thanks! I was able to get upto ~9M/s this morning. Guess the server might have been overloaded at the time. I'll reopen if this is a persistent problem.
