### ISSUE TITLE
模型怎么固定

### ISSUE THREAD

**Issue by guijuzhejiang** [PaddlePaddle/Knover#122]
请问推理生成对话时，模型权重要怎么固定？有类似model.eval()的方法吗？

**Comment by sserdoubleh** [comment]
使用infer_step调用生成是不会修改模型权重的，不需要用户调用这种接口

**Comment by guijuzhejiang** [comment]
谢谢，args.run_infer = True这个参数设定应该就是了。分享个解决的预测问题（也不算bug，根据自己的需要吧）：
knover/tasks/dialog_generation.py:401  ：context = post_process_context(ctx_token_ids, reader, merge=False)
这里要把merge=False改成True，不然再分词时会多出空格分词。这里很难发现，因为不报错，但是生成的回答会越来越离谱

**Comment by sserdoubleh** [comment]
> 谢谢，args.run_infer = True这个参数设定应该就是了。分享个解决的预测问题（也不算bug，根据自己的需要吧）： knover/tasks/dialog_generation.py:401 ：context = post_process_context(ctx_token_ids, reader, merge=False) 这里要把merge=False改成True，不然再分词时会多出空格分词。这里很难发现，因为不报错，但是生成的回答会越来越离谱

你提到的这个问题有点奇怪哈，生成的时候计算nsp得分，因为直接使用的是生成模型生成出来的回复，是已经分词好的，所以设置成tokenized的data_format，按理说不需要merge，我检查了下现在的代码，发现接口变了（之前是用`tokenized_input=True`，现在需要用`data_format="tokenized"`），我后续改一下
https://github.com/PaddlePaddle/Knover/blob/dae9686c333a2b239d6726729eb7a80bb399e309/knover/tasks/dialog_generation.py#L381

非常感谢反馈哈~

**Comment by guijuzhejiang** [comment]
非常感谢，关闭
