### ISSUE TITLE
About PLATO-KAG

### ISSUE THREAD

**Issue by bingfeiz** [PaddlePaddle/Knover#128]
First of all thank you very much for your work. When I run the code of PLATO-KAG as instructed, there is a problem.
![problem](https://user-images.githubusercontent.com/96398485/163391312-305b3c1d-78ff-40ed-baf6-753bcb93ee59.png)
Would you mind answering this question？thank you very much.

**Comment by Vonderland** [comment]
Thanks for your attention to this work!
Please try the latest version of Knover (should include https://github.com/PaddlePaddle/Knover/pull/131) to check whether it is ok.

**Comment by bingfeiz** [comment]
![image](https://user-images.githubusercontent.com/96398485/163791628-72f804ff-23c5-422f-b949-c6d1b3751b30.png)
There still seems to be a problem

**Comment by Vonderland** [comment]
Could you please show the results of 
`ls -l ./projects/PLATO-KAG/wow/train.sh`
 and 
`ls -l ./scripts/local/job.sh`?

**Comment by bingfeiz** [comment]
![1650279250(1)](https://user-images.githubusercontent.com/96398485/163798771-11a982eb-6a96-4780-96f3-ffab15686838.jpg)

**Comment by Vonderland** [comment]
Please excute
`chmod +x ./projects/PLATO-KAG/*/*.sh`
and
`chmod +x ./scripts/*/*.sh`
before running the scripts of the project.

By the way, do you get the codes of Knover by git clone or downloading the ZIP?

**Comment by bingfeiz** [comment]
Thanks for your answer, the problem has been solved, I forgot to give permission to job.sh
