### ISSUE TITLE
XLarge模型部署需要多大显存

### ISSUE THREAD

**Issue by guijuzhejiang** [PaddlePaddle/Knover#157]
感谢分享的XLarge模型，请问部署一个11B参数的XLarge模型至少需要大多显存？

**Comment by sserdoubleh** [comment]
部署fp32的模型需要两张 V100 32G，如果使用 fp16可以做到单张 V100 32G部署
如果想使用高速的推理可以参考这里：
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/plato-xl

**Comment by guijuzhejiang** [comment]
谢谢，关闭问题
