### ISSUE TITLE
如何使用Plato-KAG训练自己的数据

### ISSUE THREAD

**Issue by guijuzhejiang** [PaddlePaddle/Knover#158]
非常感谢你们开源的工作，去年我用了plato2训练了自己的模型，但不基于知识回答的很随意。请问如果使用Plato-KAG训练自己的模型，有没有相关的指导文档，比如数据处理，训练步骤等。提前致谢

**Comment by sserdoubleh** [comment]
以 WoW 为例，训练可以参考下面脚本里的处理流程
https://github.com/PaddlePaddle/Knover/blob/develop/projects/PLATO-KAG/wow/train.sh
包含训练数据处理 & 启动训练

**Comment by guijuzhejiang** [comment]
谢谢回复，这个脚本看过了。这种带有知识的数据是怎么制作的？还有其他开源的知识数据吗？

**Comment by sserdoubleh** [comment]
带知识的对话数据的构建，可以看 WoW 原论文哈
中文开源对话数据的话，可以在千言上找一找：https://www.luge.ai/

**Comment by guijuzhejiang** [comment]
感谢感谢，马上学习一下：）
