### ISSUE TITLE
*_plato_interact.sh bug

### ISSUE THREAD

**Issue by kinghuin** [PaddlePaddle/Knover#17]
https://github.com/PaddlePaddle/Knover/blob/master/plato-2/scripts/24L_plato_interact.sh#L18
这个地方的文件名和使用方式已经修改了，但是这里没有改。
为什么不能提供包含__model__的ckpt下载呢？

**Comment by sserdoubleh** [comment]
https://github.com/PaddlePaddle/Knover/pull/19
我先把这个从脚本层面上修复，后续我们会重新上传模型

**Comment by sserdoubleh** [comment]
模型已经重新上传
