### ISSUE TITLE
PLATO stage1训练发现内存一直在增长，训练到9w步后，出现内存溢出，这是什么原因？

### ISSUE THREAD

**Issue by yiyele** [PaddlePaddle/Knover#175]
使用中文的的语料训练plato，但是发现训练到一定步数后，内存就被消耗完了，这是什么原因？

**Comment by sserdoubleh** [comment]
大概率是因为，你的 data_format 为 raw 导致的
https://github.com/PaddlePaddle/Knover/blob/24636efbec32cbcd5dafa3cc38530c066b808e3f/knover/utils/tokenization.py#L158
knover 对于这一格式，采用了缓存分词结果的方式，加速数据处理；这个数据格式主要是简单，方便，易于理解，但是性能较差

对于大规模的数据，就不建议采用该 data_format 格式，建议采用 numerical 格式
你可以更新到最新代码，参考 https://github.com/PaddlePaddle/Knover/blob/develop/knover/tools/pre_numericalize.sh ，将你的数据转为 numerical 格式

**Comment by yiyele** [comment]
好的，我试试，能加个联系方式吗？有问题随时找你沟通。
















在 2022-12-19 18:39:51，"sserdoubleh" ***@***.***> 写道：

大概率是因为，你的 data_format 为 raw 导致的
https://github.com/PaddlePaddle/Knover/blob/24636efbec32cbcd5dafa3cc38530c066b808e3f/knover/utils/tokenization.py#L158
knover 对于这一格式，采用了缓存分词结果的方式，加速数据处理；这个数据格式主要是简单，方便，易于理解，但是性能较差

对于大规模的数据，就不建议采用data_format 格式，建议采用 numerical 格式
你可以更新到最新代码，参考 https://github.com/PaddlePaddle/Knover/blob/develop/knover/tools/pre_numericalize.sh ，将你的数据转为 numerical 格式

**Comment by yiyele** [comment]
使用numerical开始训练，但是会出现loss为nan的情况，这是怎么回事？
@sserdoubleh

**Comment by sserdoubleh** [comment]
是训练一开始就出现nan 吗？

**Comment by yiyele** [comment]
应该是没问题了，我调整了warmup。
@sserdoubleh
