### ISSUE TITLE
PLATO-KAG生成的回复能否使用NSP模型的score排序

### ISSUE THREAD

**Issue by guijuzhejiang** [PaddlePaddle/Knover#177]
请问在知识应答PLATO-KAG生成应答后，能否使用plato2的stage2.2的NSP任务模型的输出score作排序？尝试设置--ranking_score nsp_score，运行失败了

**Comment by sserdoubleh** [comment]
https://github.com/PaddlePaddle/Knover/blob/develop/docs/usage.md#inference
参考这里，需要设置 nsp_init_params
这个 nsp_init_params 是一个推理模型目录，下面有 __model__ 这样的模型结果文件

**Comment by guijuzhejiang** [comment]
谢谢，那和plato2的nsp_init_params参数用法一样。
