### ISSUE TITLE
关于PLATO-KAG模型部署后的回答生成

### ISSUE THREAD

**Issue by guijuzhejiang** [PaddlePaddle/Knover#178]
学习了./scripts/single_gpu/infer.sh脚本，里面有build data，eval ppl，generation，eval F1等几个脚本组成。如果我只想根据输入数据和知识生成回答的话，是否只要跑infer_generation.conf这一个脚本就够了？我看论文里是分知识排序选择和根据选择的知识来生成回复两步，KAG模型部署后，是否也需要先运行一次选择知识，再运行第二次生成回复两步呢？

**Comment by sserdoubleh** [comment]
1. 只需要输入上文和知识生成回答，只需要跑 infer_generation.conf
2. 如果知识库比当时训练时喂给生成模型的知识数量多，是需要做预先做一次选择，减小知识候选集大小

**Comment by guijuzhejiang** [comment]
明白了，谢谢
