### ISSUE TITLE
KAG训练中mean_mlm_ce指标的意义是什么

### ISSUE THREAD

**Issue by guijuzhejiang** [PaddlePaddle/Knover#180]
在plato2-KAG模型的训练过程中有两个评价指标：loss和mean_mlm_ce，猜测loss是生成的回答和训练数据中tgt之间的损失，mean_mlm_ce是否衡量知识选择的正确概率？

**Comment by sserdoubleh** [comment]
loss 就是论文中的联合训练 loss
mean_mlm_ce 是个参考值，表示对使用每个 knowledge 的 NLL loss 进行直接取平均，而联合训练 loss 类似于对 knowledge 进行加权

**Comment by guijuzhejiang** [comment]
谢谢，明白了。
