### ISSUE TITLE
lr scheduler参数设置

### ISSUE THREAD

**Issue by guijuzhejiang** [PaddlePaddle/Knover#182]
看到有关lr scheduler设置的代码：group.add_argument("--lr_scheduler", type=str, default="noam", choices=["linear", "noam", "constant", "cosine"],是否可以在训练的conf中设置--lr_scheduler？

**Comment by sserdoubleh** [comment]
可以的
可以直接在train_args里面加上，比如
```
train_args="
--lr_scheduler linear
--max_decay_steps 2000
"
```

**Comment by guijuzhejiang** [comment]
谢谢回复，请问数据量比较大时，用哪种lr_scheduler比较好？用的默认的noam，一个epoch刚训到1/6左右,lr已经衰减到1e-6了，学习率过小会不会造成后面的数据训练不充分，收敛慢？

**Comment by sserdoubleh** [comment]
如果使用的是默认的noam，增大 warmup_steps 比较好
也可以用简单的linear decay（不同的scheduler对效果影响不大），max_decay_step设置成你要训练的step数就好

**Comment by guijuzhejiang** [comment]
谢谢，还是用linear试试
