### ISSUE TITLE
可以用CPU运行interact吗？

### ISSUE THREAD

**Issue by fancyerii** [PaddlePaddle/Knover#22]
用gpu运行plato-2/scripts/24L_plato_interact.sh是可以的，但是我在没有gpu的机器上安装了cpu版本的paddlepaddle运行时出现问题：
E0811 21:28:37.228886 20545 pybind.cc:1277] Cannot use GPU because you have installed CPU version PaddlePaddle.
If you want to use GPU, please try to install GPU version PaddlePaddle by: pip install paddlepaddle-gpu
If you only have CPU, please change CUDAPlace(0) to be CPUPlace().

我已经尝试把所有的CUDAPlace(0)都替换成了CPUPlace()，请问还有哪不对吗？。
这是git diff的结果：

https://gist.github.com/fancyerii/fa04cea4e94cf9408c5d6091697fd9fa

**Comment by sserdoubleh** [comment]
可以用CPU进行interact
你还差一个地方没有改掉
https://github.com/PaddlePaddle/Knover/blob/15d5279a4370b225b0c388a129b774c9469fcde4/utils/inference.py#L30

**Comment by fancyerii** [comment]
可以了，谢谢！
