### ISSUE TITLE
请问一下论文中的L_{BOW}

### ISSUE THREAD

**Issue by fancyerii** [PaddlePaddle/Knover#27]
根据论文：
![图片](https://user-images.githubusercontent.com/5372812/90515822-c46bd780-e195-11ea-8f07-dd7500e254f8.png)

我的理解是：topic隐变量z对于的向量h_z乘以W_2，W_2 \in R^{V \times D}为每一个词的向量，这样就可以一次计算z和所有词的内积，然后softmax变成概率。然后我们优化的目标是target里出现的词对应的logits大，从而loss小。如果是这样的话，为什么又对f_{r_t}再计算一次softmax呢？

**Comment by portia1026** [comment]
非常感谢指出这个问题，公式(5)中确实是有typo，是多写了softmax，网络里f函数的估计，只是经过MLP，并没有softmax这个操作。

**Comment by LLLLLLoki** [comment]
您好，这论文你的题目是什么啊？有空能发一下吗

**Comment by portia1026** [comment]
> 这论文你的题目是什么啊？

PLATO-2: Towards Building an Open-Domain Chatbot via Curriculum Learning
ArXiv链接 https://arxiv.org/abs/2006.16779
