### ISSUE TITLE
运行convert_data_to_numerical时需要"sentence_piece_model"

### ISSUE THREAD

**Issue by 27182812** [PaddlePaddle/Knover#29]
请问这个sentence_piece_model是需要自己准备的吗？另外如何使用这个模型的文档可以详细点吗，或者说可能是我自己没找到详细说明的地方。工作很好，不过作为一个新手上手有点困难欸，麻烦解答了，谢谢。

**Comment by sserdoubleh** [comment]
https://github.com/PaddlePaddle/Knover/tree/luge-dialogue/luge-dialogue/config
可以使用这个目录下的spm.model

**Comment by 27182812** [comment]
哦哦好的，谢谢啦
