### ISSUE TITLE
期待更新中文模型

### ISSUE THREAD

**Issue by AnShengqiang** [PaddlePaddle/Knover#3]

**Comment by bojone** [comment]
建议不要就说一个“soom”，要发布就说一个明确的时间，哪怕是一个时间段也好，免得浪费大家时间。

**Comment by Jeff654** [comment]
希望尽快看到发布的语料和模型

**Comment by terrifyzhao** [comment]
期待

**Comment by codelast** [comment]
文档如此不完善，为什么要急着发布呢？完成开源KPI吗？

**Comment by bladetornado** [comment]
感谢各位的建议和意见。 Knover致力于成为百度开放域对话，特别是知识引导的开放域对话相关对话技术开放的窗口。目前阶段，我们会逐步开放基于英文语料训练的模型和训练代码。但中文模型和语料暂时不在开源之列。我们可能将于近期开放中英文对话的体验接口。长期阶段，Knover会不断融合并开放百度开放域对话的最新技术，不断推进开放域对话的技术前沿。欢迎大家关注。

与此同时，大家可以关注百度发布的一些新的数据集，包括[知识驱动对话](https://aistudio.baidu.com/aistudio/datasetdetail/13188)，[面向推荐的对话](https://aistudio.baidu.com/aistudio/competition/detail/29?isFromCcf=true)等等。 

Thanks for the suggestions.  Knover is an open-source repo demonstrating the most advanced technologies in open-domain dialogue systems from Baidu.  We will gradually open the training and the inference code, and we have opened the English model. However, the Chinese model and the full training corpus will not be open-source right now. We may also release the service for English and Chinese conversation in the near future, please stay tuned if you are interested. Thanks a lot.

At the same time, Baidu has published a bunch of datasets on this topic, including the [DuConv](https://aistudio.baidu.com/aistudio/datasetdetail/13188) and the [DuRecDial](https://aistudio.baidu.com/aistudio/competition/detail/29?isFromCcf=true). More resources are on the way.

**Comment by bladetornado** [comment]
感谢各位的建议和意见。 Knover致力于成为百度开放域对话，特别是知识引导的开放域对话相关对话技术开放的窗口。目前阶段，我们会逐步开放基于英文语料训练的模型和训练代码。但中文模型和语料暂时不在开源之列。我们可能将于近期开放中英文对话的体验接口。长期阶段，Knover会不断融合并开放百度开放域对话的最新技术，不断推进开放域对话的技术前沿。欢迎大家关注。

与此同时，大家可以关注百度发布的一些新的数据集，包括[DuConv](https://aistudio.baidu.com/aistudio/datasetdetail/13188)，[DuRecDial](https://aistudio.baidu.com/aistudio/competition/detail/29?isFromCcf=true)等等。

Thanks for the suggestions. Knover is an open-source repo demonstrating the most advanced technologies in open-domain dialogue systems from Baidu. We will gradually open the training and the inference code, and we have opened the English model. However, the Chinese model and the full training corpus will not be open-source right now. We may also release the service for English and Chinese conversation shortly; please stay tuned if you are interested. Thanks a lot.

At the same time, Baidu has published a bunch of datasets on this topic, including the [DuConv](https://aistudio.baidu.com/aistudio/datasetdetail/13188)，[DuRecDial](https://aistudio.baidu.com/aistudio/competition/detail/29?isFromCcf=true). More resources are on the way.

**Comment by bojone** [comment]
> 感谢各位的建议和意见。 Knover致力于成为百度开放域对话，特别是知识引导的开放域对话相关对话技术开放的窗口。目前阶段，我们会逐步开放基于英文语料训练的模型和训练代码。但中文模型和语料暂时不在开源之列。我们可能将于近期开放中英文对话的体验接口。长期阶段，Knover会不断融合并开放百度开放域对话的最新技术，不断推进开放域对话的技术前沿。欢迎大家关注。
> 
> 与此同时，大家可以关注百度发布的一些新的数据集，包括[DuConv](https://aistudio.baidu.com/aistudio/datasetdetail/13188)，[DuRecDial](https://aistudio.baidu.com/aistudio/competition/detail/29?isFromCcf=true)等等。
> 
> Thanks for the suggestions. Knover is an open-source repo demonstrating the most advanced technologies in open-domain dialogue systems from Baidu. We will gradually open the training and the inference code, and we have opened the English model. However, the Chinese model and the full training corpus will not be open-source right now. We may also release the service for English and Chinese conversation shortly; please stay tuned if you are interested. Thanks a lot.
> 
> At the same time, Baidu has published a bunch of datasets on this topic, including the [DuConv](https://aistudio.baidu.com/aistudio/datasetdetail/13188)，[DuRecDial](https://aistudio.baidu.com/aistudio/competition/detail/29?isFromCcf=true). More resources are on the way.

意料之中，连ernie 2.0、ernie-gen都不舍得开源，怎么可能轮得到开源对话模型和语料，大家散了吧～

**Comment by Jeff654** [comment]
> 基于英文语料训练的模型和训练代码。

英文预料训练的模型和代码什么时候开源，英文语料会提供么？可否提供一个具体的时间点

**Comment by portia1026** [comment]
我们的PLATO-2英文模型（310M & 1.6B），inference代码（支持回复生成 & 动态交互），以及生成模型的训练代码，已经开源了，在[plato-2](https://github.com/PaddlePaddle/Knover/tree/master/plato-2)的页面里。

**Comment by portia1026** [comment]
关于英文训练语料，是Reddit的评论信息，是由第三方爬取的，我们文章里有进行说明。这里是[链接](https://files.pushshift.io/reddit/)，大家也可以download进行处理。

**Comment by AnShengqiang** [comment]
百度在中文nlp开源上的贡献是值得肯定的，因为商业原因闭源也能理解。issue关闭了。

**Comment by bojone** [comment]
> 百度在中文nlp开源上的贡献是值得肯定的，因为商业原因闭源也能理解。issue关闭了。

请问除了一个不上不下的ernie 1.0还有啥是开源的？只开源代码也叫开源？只要有想法，随随便便用个tf或pytorch的训练代码都可以改出来了吧？大家不就是缺语聊或者缺权重吗？既然不开源语料也不开源权重，那就别号称开源，至少别号称在中文领域开源。

**Comment by AnShengqiang** [comment]
> > 百度在中文nlp开源上的贡献是值得肯定的，因为商业原因闭源也能理解。issue关闭了。
> 
> 请问除了一个不上不下的ernie 1.0还有啥是开源的？只开源代码也叫开源？只要有想法，随随便便用个tf或pytorch的训练代码都可以改出来了吧？大家不就是缺语聊或者缺权重吗？既然不开源语料也不开源权重，那就别号称开源，至少别号称在中文领域开源。

嗯，所以对百度的做法只能理解，并不赞同。开源个小中文模型给大家用用也比只开源英文模型好。之前打算使用paddle体系的，也是因为现在百度半开半闭的态度放弃了。
