### ISSUE TITLE
the missing full source code of plato-2

### ISSUE THREAD

**Issue by chikiuso** [PaddlePaddle/Knover#32]
Hi thanks for your great work! I explore the plato-2 directory and just found there are .sh files, may I ask where is the .py files? so I could try the chatbot interaction, thanks for your help!

**Comment by sserdoubleh** [comment]
You can run `git clone https://github.com/PaddlePaddle/Knover.git`
PLATO-2 model implement is in `models/plato.py`
If you want to run interaction, you can run scripts fllowing `plato-2/README.md`

**Comment by chikiuso** [comment]
@sserdoubleh thanks for your help, I run it finally, but it halts on this screen :

https://ibb.co/VpbQwp2

**Comment by sserdoubleh** [comment]
> @sserdoubleh thanks for your help, I run it finally, but it halts on this screen :
> 
> https://ibb.co/VpbQwp2

What about the version of PaddlePaddle?

**Comment by sserdoubleh** [comment]
https://github.com/PaddlePaddle/Knover/issues/11
Perhaps because of the version of CUDA, PaddlePaddle cannot support CUDA 11.0 now.

**Comment by chikiuso** [comment]
@sserdoubleh thanks for your help, I work now. is this project possible to add persona or personality to the chat bot? if yes, what procedure should I follow to fine-tune it to a personalized chat bot? thanks.

**Comment by sserdoubleh** [comment]
> @sserdoubleh thanks for your help, I work now. is this project possible to add persona or personality to the chat bot? if yes, what procedure should I follow to fine-tune it to a personalized chat bot? thanks.


https://github.com/PaddlePaddle/Knover/issues/24#issuecomment-673340869
This may be helpful.

If you want to fine-tune your model with persona, you can check the data formt in `data/train.tsv`  and the description in `README.md` on the root path.

**Comment by chikiuso** [comment]
Hi @sserdoubleh,  thanks for your help, I now could run the 24L model interact on server, is it possible to make it work with cuda 11.0 or above? or could you point some way I could try to modify the code to make it cuda 11.0 compatible? as the latest gpu all run cuda 11.0 or above.

thanks for your great help in the last several days, your responsive reply make it a successful paper and project.

**Comment by sserdoubleh** [comment]
@chikiuso I have sent the feedback to PaddlePaddle. Maybe it need time to support CUDA11.0. If it has any progress, I will notice you.

May be you can try to re-compile your PaddlePadle~
https://www.paddlepaddle.org.cn/documentation/docs/en/install/compile/compile_Ubuntu_en.html
git checkout release/1.8

**Comment by chikiuso** [comment]
Hi @sserdoubleh , thanks for your help, I just compiled paddlepaddle from source and have a try but failed , may be I wait for the paddlepaddle upgrade support, thanks a lot!
