### ISSUE TITLE
请问NSPModel是如何训练的？

### ISSUE THREAD

**Issue by zhiyingf** [PaddlePaddle/Knover#33]

**Comment by fiyen** [comment]
同问。

**Comment by sserdoubleh** [comment]
train config改成
```
task=NextSentencePrediction
model=NSPModel

train_args="--mix_negative_sample true"
```

**Comment by fiyen** [comment]
这个链接仅供参考：https://aistudio.baidu.com/aistudio/projectdetail/1109114

**Comment by zhiyingf** [comment]
> train config改成
> 
> ```
> task=NextSentencePrediction
> model=NSPModel
> 
> train_args="--mix_negative_sample true"
> ```

啊，还是不行。从开始的参数错位，到label=None，（加了train_args="--mix_negative_sample true"之后）再到现在的AttributeError:'NSPRdear' object has no attribute 'max_seq_len'。
此外，关于plato-2的训练，NSPModel和Plato是分开训练吗？但是我今天看Plato论文的时候发现是两个是放在一起训练，共享参数，计算总的loss，在最后更新权重。这里有点迷惑。

**Comment by zhiyingf** [comment]
> 这个链接仅供参考：https://aistudio.baidu.com/aistudio/projectdetail/1109114

感谢，那我好好看看。

**Comment by fiyen** [comment]
> > 这个链接仅供参考：https://aistudio.baidu.com/aistudio/projectdetail/1109114
> 
> 感谢，那我好好看看。

刚好你上边提到的问题我也遇到了。我提出了解决方法。你可以参考一下。

**Comment by zhiyingf** [comment]
> > > 这个链接仅供参考：https://aistudio.baidu.com/aistudio/projectdetail/1109114
> > 
> > 
> > 感谢，那我好好看看。
> 
> 刚好你上边提到的问题我也遇到了。我提出了解决方法。你可以参考一下。

啊，刚好看见了！

**Comment by zhiyingf** [comment]
> train config改成
> 
> ```
> task=NextSentencePrediction
> model=NSPModel
> 
> train_args="--mix_negative_sample true"
> ```

啊，还是不行。从开始的参数错位，到label=None，（加了train_args="--mix_negative_sample true"之后）再到现在的AttributeError:'NSPRdear' object has no attribute 'max_seq_len'。
但是最后参考https://aistudio.baidu.com/aistudio/projectdetail/1109114，在NSP_Reader.py的__init__中加入self.max_seq_len = args.max_seq_len就解决了！
此外，关于plato-2的训练，NSPModel和Plato是分开训练吗？但是我今天看Plato论文的时候发现是两个是放在一起训练，共享参数，计算总的loss，在最后更新权重。这里有点迷惑。

**Comment by fiyen** [comment]
> > train config改成
> > ```
> > task=NextSentencePrediction
> > model=NSPModel
> > 
> > train_args="--mix_negative_sample true"
> > ```
> 
> 啊，还是不行。从开始的参数错位，到label=None，（加了train_args="--mix_negative_sample true"之后）再到现在的AttributeError:'NSPRdear' object has no attribute 'max_seq_len'。
> 但是最后参考[https://aistudio.baidu.com/aistudio/projectdetail/1109114，在NSP_Reader.py的__init__中加入self.max_seq_len](https://aistudio.baidu.com/aistudio/projectdetail/1109114%EF%BC%8C%E5%9C%A8NSP_Reader.py%E7%9A%84__init__%E4%B8%AD%E5%8A%A0%E5%85%A5self.max_seq_len) = args.max_seq_len就解决了！
> 此外，关于plato-2的训练，NSPModel和Plato是分开训练吗？但是我今天看Plato论文的时候发现是两个是放在一起训练，共享参数，计算总的loss，在最后更新权重。这里有点迷惑。

这个我也纠结了好久。但是Plato-2的论文中分成了2.1和2.2两步，而且都用了10w步训练，学习率也不一样。
![image](https://user-images.githubusercontent.com/35953131/100352272-b5fc4a00-3027-11eb-9b2d-70eb180993a9.png)
所以我感觉应该是分开的。但是我也不是很确定。还是要请Siqi Bao大神来解一下疑惑 。

**Comment by fiyen** [comment]
> > train config改成
> > ```
> > task=NextSentencePrediction
> > model=NSPModel
> > 
> > train_args="--mix_negative_sample true"
> > ```
> 
> 啊，还是不行。从开始的参数错位，到label=None，（加了train_args="--mix_negative_sample true"之后）再到现在的AttributeError:'NSPRdear' object has no attribute 'max_seq_len'。
> 但是最后参考[https://aistudio.baidu.com/aistudio/projectdetail/1109114，在NSP_Reader.py的__init__中加入self.max_seq_len](https://aistudio.baidu.com/aistudio/projectdetail/1109114%EF%BC%8C%E5%9C%A8NSP_Reader.py%E7%9A%84__init__%E4%B8%AD%E5%8A%A0%E5%85%A5self.max_seq_len) = args.max_seq_len就解决了！
> 此外，关于plato-2的训练，NSPModel和Plato是分开训练吗？但是我今天看Plato论文的时候发现是两个是放在一起训练，共享参数，计算总的loss，在最后更新权重。这里有点迷惑。

而且源代码中对NSPModel的引入，是在构建模型参数之外的。感觉上没办法使NSPModel的参数跟着Plato一块优化。

**Comment by zhiyingf** [comment]
> > > train config改成
> > > ```
> > > task=NextSentencePrediction
> > > model=NSPModel
> > > 
> > > train_args="--mix_negative_sample true"
> > > ```
> > 
> > 
> > 啊，还是不行。从开始的参数错位，到label=None，（加了train_args="--mix_negative_sample true"之后）再到现在的AttributeError:'NSPRdear' object has no attribute 'max_seq_len'。
> > 但是最后参考[https://aistudio.baidu.com/aistudio/projectdetail/1109114，在NSP_Reader.py的__init__中加入self.max_seq_len](https://aistudio.baidu.com/aistudio/projectdetail/1109114%EF%BC%8C%E5%9C%A8NSP_Reader.py%E7%9A%84__init__%E4%B8%AD%E5%8A%A0%E5%85%A5self.max_seq_len) = args.max_seq_len就解决了！
> > 此外，关于plato-2的训练，NSPModel和Plato是分开训练吗？但是我今天看Plato论文的时候发现是两个是放在一起训练，共享参数，计算总的loss，在最后更新权重。这里有点迷惑。
> 
> 这个我也纠结了好久。但是Plato-2的论文中分成了2.1和2.2两步，而且都用了10w步训练，学习率也不一样。
> ![image](https://user-images.githubusercontent.com/35953131/100352272-b5fc4a00-3027-11eb-9b2d-70eb180993a9.png)
> 所以我感觉应该是分开的。但是我也不是很确定。还是要请Siqi Bao大神来解一下疑惑 。

嗯嗯，但是其实看了Plato和Plato-2这两篇论文感觉主要的改进在于Curriculum Learning，在Plato前面加了General Response Generation。而plato-2论文中似乎没有表述第二阶段如何训练。如果放在一起训练的话不知是否会好一点，毕竟二者是相互促进的。

**Comment by zhiyingf** [comment]
> > > train config改成
> > > ```
> > > task=NextSentencePrediction
> > > model=NSPModel
> > > 
> > > train_args="--mix_negative_sample true"
> > > ```
> > 
> > 
> > 啊，还是不行。从开始的参数错位，到label=None，（加了train_args="--mix_negative_sample true"之后）再到现在的AttributeError:'NSPRdear' object has no attribute 'max_seq_len'。
> > 但是最后参考[https://aistudio.baidu.com/aistudio/projectdetail/1109114，在NSP_Reader.py的__init__中加入self.max_seq_len](https://aistudio.baidu.com/aistudio/projectdetail/1109114%EF%BC%8C%E5%9C%A8NSP_Reader.py%E7%9A%84__init__%E4%B8%AD%E5%8A%A0%E5%85%A5self.max_seq_len) = args.max_seq_len就解决了！
> > 此外，关于plato-2的训练，NSPModel和Plato是分开训练吗？但是我今天看Plato论文的时候发现是两个是放在一起训练，共享参数，计算总的loss，在最后更新权重。这里有点迷惑。
> 
> 而且源代码中对NSPModel的引入，是在构建模型参数之外的。感觉上没办法使NSPModel的参数跟着Plato一块优化。

嗯嗯，plato源码好像两者模型好像是放在一起的。plato-2好像就完全分开了，Plato和NSPModel都是继承UnifiedTransformer。

**Comment by fiyen** [comment]
> > > > train config改成
> > > > ```
> > > > task=NextSentencePrediction
> > > > model=NSPModel
> > > > 
> > > > train_args="--mix_negative_sample true"
> > > > ```
> > > 
> > > 
> > > 啊，还是不行。从开始的参数错位，到label=None，（加了train_args="--mix_negative_sample true"之后）再到现在的AttributeError:'NSPRdear' object has no attribute 'max_seq_len'。
> > > 但是最后参考[https://aistudio.baidu.com/aistudio/projectdetail/1109114，在NSP_Reader.py的__init__中加入self.max_seq_len](https://aistudio.baidu.com/aistudio/projectdetail/1109114%EF%BC%8C%E5%9C%A8NSP_Reader.py%E7%9A%84__init__%E4%B8%AD%E5%8A%A0%E5%85%A5self.max_seq_len) = args.max_seq_len就解决了！
> > > 此外，关于plato-2的训练，NSPModel和Plato是分开训练吗？但是我今天看Plato论文的时候发现是两个是放在一起训练，共享参数，计算总的loss，在最后更新权重。这里有点迷惑。
> > 
> > 
> > 这个我也纠结了好久。但是Plato-2的论文中分成了2.1和2.2两步，而且都用了10w步训练，学习率也不一样。
> > ![image](https://user-images.githubusercontent.com/35953131/100352272-b5fc4a00-3027-11eb-9b2d-70eb180993a9.png)
> > 所以我感觉应该是分开的。但是我也不是很确定。还是要请Siqi Bao大神来解一下疑惑 。
> 
> 嗯嗯，但是其实看了Plato和Plato-2这两篇论文感觉主要的改进在于Curriculum Learning，在Plato前面加了General Response Generation。而plato-2论文中似乎没有表述第二阶段如何训练。如果放在一起训练的话不知是否会好一点，毕竟二者是相互促进的。

NSPModel的训练数据因为有了负采样，多了一倍。训练很慢。。。为什么不能放一块，就得@zhiyingf 请大神解一下疑惑了！！

**Comment by zhiyingf** [comment]
> > > > > train config改成
> > > > > ```
> > > > > task=NextSentencePrediction
> > > > > model=NSPModel
> > > > > 
> > > > > train_args="--mix_negative_sample true"
> > > > > ```
> > > > 
> > > > 
> > > > 啊，还是不行。从开始的参数错位，到label=None，（加了train_args="--mix_negative_sample true"之后）再到现在的AttributeError:'NSPRdear' object has no attribute 'max_seq_len'。
> > > > 但是最后参考[https://aistudio.baidu.com/aistudio/projectdetail/1109114，在NSP_Reader.py的__init__中加入self.max_seq_len](https://aistudio.baidu.com/aistudio/projectdetail/1109114%EF%BC%8C%E5%9C%A8NSP_Reader.py%E7%9A%84__init__%E4%B8%AD%E5%8A%A0%E5%85%A5self.max_seq_len) = args.max_seq_len就解决了！
> > > > 此外，关于plato-2的训练，NSPModel和Plato是分开训练吗？但是我今天看Plato论文的时候发现是两个是放在一起训练，共享参数，计算总的loss，在最后更新权重。这里有点迷惑。
> > > 
> > > 
> > > 这个我也纠结了好久。但是Plato-2的论文中分成了2.1和2.2两步，而且都用了10w步训练，学习率也不一样。
> > > ![image](https://user-images.githubusercontent.com/35953131/100352272-b5fc4a00-3027-11eb-9b2d-70eb180993a9.png)
> > > 所以我感觉应该是分开的。但是我也不是很确定。还是要请Siqi Bao大神来解一下疑惑 。
> > 
> > 
> > 嗯嗯，但是其实看了Plato和Plato-2这两篇论文感觉主要的改进在于Curriculum Learning，在Plato前面加了General Response Generation。而plato-2论文中似乎没有表述第二阶段如何训练。如果放在一起训练的话不知是否会好一点，毕竟二者是相互促进的。
> 
> NSPModel的训练数据因为有了负采样，多了一倍。训练很慢。。。为什么不能放一块，就得@zhiyingf 请大神解一下疑惑了！！

我是萌新一枚，还是请懂的人解惑一下吧。

**Comment by fiyen** [comment]
@

> train config改成
> 
> ```
> task=NextSentencePrediction
> model=NSPModel
> 
> train_args="--mix_negative_sample true"
> ```



> > > > > > train config改成
> > > > > > ```
> > > > > > task=NextSentencePrediction
> > > > > > model=NSPModel
> > > > > > 
> > > > > > train_args="--mix_negative_sample true"
> > > > > > ```
> > > > > 
> > > > > 
> > > > > 啊，还是不行。从开始的参数错位，到label=None，（加了train_args="--mix_negative_sample true"之后）再到现在的AttributeError:'NSPRdear' object has no attribute 'max_seq_len'。
> > > > > 但是最后参考[https://aistudio.baidu.com/aistudio/projectdetail/1109114，在NSP_Reader.py的__init__中加入self.max_seq_len](https://aistudio.baidu.com/aistudio/projectdetail/1109114%EF%BC%8C%E5%9C%A8NSP_Reader.py%E7%9A%84__init__%E4%B8%AD%E5%8A%A0%E5%85%A5self.max_seq_len) = args.max_seq_len就解决了！
> > > > > 此外，关于plato-2的训练，NSPModel和Plato是分开训练吗？但是我今天看Plato论文的时候发现是两个是放在一起训练，共享参数，计算总的loss，在最后更新权重。这里有点迷惑。
> > > > 
> > > > 
> > > > 这个我也纠结了好久。但是Plato-2的论文中分成了2.1和2.2两步，而且都用了10w步训练，学习率也不一样。
> > > > ![image](https://user-images.githubusercontent.com/35953131/100352272-b5fc4a00-3027-11eb-9b2d-70eb180993a9.png)
> > > > 所以我感觉应该是分开的。但是我也不是很确定。还是要请Siqi Bao大神来解一下疑惑 。
> > > 
> > > 
> > > 嗯嗯，但是其实看了Plato和Plato-2这两篇论文感觉主要的改进在于Curriculum Learning，在Plato前面加了General Response Generation。而plato-2论文中似乎没有表述第二阶段如何训练。如果放在一起训练的话不知是否会好一点，毕竟二者是相互促进的。
> > 
> > 
> > NSPModel的训练数据因为有了负采样，多了一倍。训练很慢。。。为什么不能放一块，就得@zhiyingf 请大神解一下疑惑了！！
> 
> 我是萌新一枚，还是请懂的人解惑一下吧。

@sserdoubleh 大神，请解惑！
