### ISSUE TITLE
多轮对话训练数据的组织

### ISSUE THREAD

**Issue by lonelydancer** [PaddlePaddle/Knover#49]
有关多轮对话训练数据组织，我有个疑问。
比如 a, b , c， d  是一段对话。
应该生成 a,b ,c ->d一个pair的数据，还是枚举所有上文生成下文 a b,  a b ->c, abc->d 呢。

第一种方式好像会损失一些tgt，只学最后一句；
第二种方式又显得有些冗余。

**Comment by sserdoubleh** [comment]
多轮对话的训练一般按第二种方式处理

**Comment by lonelydancer** [comment]
多谢！
