### ISSUE TITLE
有关训练效果

### ISSUE THREAD

**Issue by lonelydancer** [PaddlePaddle/Knover#53]
530w数据，从头训stage1, stage2.1 。仍然明显有safe response&重复的现象，请问是我训练的不够充分吗？
stage1 batch_size=16 训练了320000 step，stage2.1训练了batch_size=1024 18000step

![image](https://user-images.githubusercontent.com/548443/117535483-8d419d00-b028-11eb-8155-a89a11c8261a.png)

改成选随机的候选感觉好一些。
![image](https://user-images.githubusercontent.com/548443/117536265-aa786a80-b02c-11eb-8b1e-88595bdc9e6a.png)

**Comment by sserdoubleh** [comment]
这两个图的 infer 设置是怎么样的？能详细说说吗？

**Comment by lonelydancer** [comment]
这两个图都是用stage2.1的训出来的model， 只不过图2，我把dialog_task中的取最高得分的response改成了随机的。
vocab_path="./package/dialog_cn/med.vocab"
spm_model_file="./package/dialog_cn/med.model"
infer_file="./data/valid_filelist"
data_format="raw"
file_format="filelist"
config_path="./package/dialog_cn/plato/24L.json"
output_name="response"
save_path="output"
model=Plato
task=DialogGeneration
do_generation=true
is_distributed=false

**Comment by sserdoubleh** [comment]
你没有使用stage 2.2的模型吧？2.1的模型不同 latent 之间的 score 不具备可比性

**Comment by lonelydancer** [comment]
是的。我还没用2.2。看来2.2是必选的了？

**Comment by sserdoubleh** [comment]
你可以试着在interaction.py里面加上task.debug()，看一下bot产生的候选回复的质量
2.2的评估模型更多是起到过滤的作用，去掉明显不好的
相比直接使用随机候选会好一些

lonelydancer ***@***.***> 于2021年5月11日周二 下午2:38写道：

**Comment by lonelydancer** [comment]
关于课程学习这个模式， 比如我已经有一版了。效果不理想，要接着训。 stage1重训之后， stage2就得根据stage1从头来训练了；没法在之前stage2基础上接着训练了吧。

**Comment by sserdoubleh** [comment]
不知道你指的效果不理想，是指stage 2.1的模型生成效果不佳，还是stage 1的模型生成效果不佳？如果改的比较多，是需要从stage 1开始训起的

**Comment by zhanghaoie** [comment]
@lonelydancer 嗨，你这边训练的时候，多轮的会话你是当一个训练数据喂给模型的，还是拆分成多个训练数据啊？训练的时候中文必须设置is_cn=True吗？

**Comment by sserdoubleh** [comment]
> @lonelydancer 嗨，你这边训练的时候，多轮的会话你是当一个训练数据喂给模型的，还是拆分成多个训练数据啊？训练的时候中文必须设置is_cn=True吗？

is_cn目前只是用在inference阶段的重复性判断上，中英文的n-gram repetition判断有些不同，英文是对word计算n-gram，中文是对字计算n-gram @zhanghaoie

**Comment by lonelydancer** [comment]
> @lonelydancer 嗨，你这边训练的时候，多轮的会话你是当一个训练数据喂给模型的，还是拆分成多个训练数据啊？训练的时候中文必须设置is_cn=True吗？

我拆分了多条,跟开发者交流过。

**Comment by lonelydancer** [comment]
stage1&stage2.1又多训了，感觉很容易重复。不清楚这种情况普遍吗?
![image](https://user-images.githubusercontent.com/548443/120305984-f9e84880-c303-11eb-990a-cba786d98268.png)

**Comment by sserdoubleh** [comment]
> stage1&stage2.1又多训了，感觉很容易重复。不清楚这种情况普遍吗?
> ![image](https://user-images.githubusercontent.com/548443/120305984-f9e84880-c303-11eb-990a-cba786d98268.png)

交互的时候有加入"--is_cn true"的选项吗？
可以在train.py里面，task创建之后加一句"task.debug()"，看看各个候选是怎么样的

**Comment by lonelydancer** [comment]
@sserdoubleh 有加入了，并且我改成从候选random抽取跑了多次，BLUE上都不如我的gpt baseline。

**Comment by sserdoubleh** [comment]
> @sserdoubleh 有加入了，并且我改成从候选random抽取跑了多次，BLUE上都不如我的gpt baseline。

使用相同语料训练的吧，验证集的 lm_loss 怎么样的呢？

**Comment by lonelydancer** [comment]
语料是一样的。
step 20:lm_loss: 3.0212, ppl: 20.5160, loss: 8.7359, bow_loss: 6.4406, entropy_loss: -0.2471
step 40:lm_loss: 3.1051, ppl: 22.3108, loss: 8.4920, bow_loss: 6.7316, entropy_loss: -0.2360

**Comment by portia1026** [comment]
@lonelydancer 可能有以下几个问题，导致效果上欠佳：
1）从 stage 2.1 模型里，随机选一个回复，这个可能不是很好的策略，虽然对话里存在一对多现象，但是不代表 针对任何一个对话上文，20 latent 方向都是合适的，最好配合 stage 2.2 评估模型，一起使用。
2）大规模预训练模型比较容易产生重复的回复，大家常用的策略是进行回复重复检测，去掉一些候选（对于这个策略，可以参考 Meena 论文 section 5.2 的讨论，https://arxiv.org/pdf/2001.09977.pdf），在 knover 中，也有相应的代码逻辑，可以考虑引入一下。
3）对于对话效果评估，BLEU 这种词重叠指标，可能只能作为参考，最终效果推荐还是人工评估看看。

**Comment by sserdoubleh** [comment]
> 语料是一样的。
> step 20:lm_loss: 3.0212, ppl: 20.5160, loss: 8.7359, bow_loss: 6.4406, entropy_loss: -0.2471
> step 40:lm_loss: 3.1051, ppl: 22.3108, loss: 8.4920, bow_loss: 6.7316, entropy_loss: -0.2360

看这个loss，感觉不是很正常；plato-2分支的代码训练部分有些问题，你训练的时候是用plato-2分支的吗？
最好切换到develop分支训练，这个已经修复了训练问题 @lonelydancer

**Comment by lonelydancer** [comment]
> @lonelydancer 可能有以下几个问题，导致效果上欠佳：
> 1）从 stage 2.1 模型里，随机选一个回复，这个可能不是很好的策略，虽然对话里存在一对多现象，但是不代表 针对任何一个对话上文，20 latent 方向都是合适的，最好配合 stage 2.2 评估模型，一起使用。
> 2）大规模预训练模型比较容易产生重复的回复，大家常用的策略是进行回复重复检测，去掉一些候选（对于这个策略，可以参考 Meena 论文 section 5.2 的讨论，[https://arxiv.org/pdf/2001.09977.pdf），在](https://arxiv.org/pdf/2001.09977.pdf%EF%BC%89%EF%BC%8C%E5%9C%A8) knover 中，也有相应的代码逻辑，可以考虑引入一下。
> 3）对于对话效果评估，BLEU 这种词重叠指标，可能只能作为参考，最终效果推荐还是人工评估看看。

关于2)，interact代码里应该已经引入了去重策略把。

**Comment by lonelydancer** [comment]
> > 语料是一样的。
> > step 20:lm_loss: 3.0212, ppl: 20.5160, loss: 8.7359, bow_loss: 6.4406, entropy_loss: -0.2471
> > step 40:lm_loss: 3.1051, ppl: 22.3108, loss: 8.4920, bow_loss: 6.7316, entropy_loss: -0.2360
> 
> 看这个loss，感觉不是很正常；plato-2分支的代码训练部分有些问题，你训练的时候是用plato-2分支的吗？
> 最好切换到develop分支训练，这个已经修复了训练问题 @lonelydancer

确实是用plato-2分支训练的。
@sserdoubleh 能具体讲一下plato-2分支里训练的哪块存在问题吗？

**Comment by lonelydancer** [comment]
用develop训了stage1，看下面这种training loss正常吗?
![image](https://user-images.githubusercontent.com/548443/120994854-7ae98900-c7b7-11eb-8124-4d80ff57e6e9.png)

**Comment by sserdoubleh** [comment]
> > > 语料是一样的。
> > > step 20:lm_loss: 3.0212, ppl: 20.5160, loss: 8.7359, bow_loss: 6.4406, entropy_loss: -0.2471
> > > step 40:lm_loss: 3.1051, ppl: 22.3108, loss: 8.4920, bow_loss: 6.7316, entropy_loss: -0.2360
> > 
> > 
> > 看这个loss，感觉不是很正常；plato-2分支的代码训练部分有些问题，你训练的时候是用plato-2分支的吗？
> > 最好切换到develop分支训练，这个已经修复了训练问题 @lonelydancer
> 
> 确实是用plato-2分支训练的。
> @sserdoubleh 能具体讲一下plato-2分支里训练的哪块存在问题吗？

Paddle 1.8的gather OP存在bug，换用gather_nd OP了

**Comment by sserdoubleh** [comment]
> 用develop训了stage1，看下面这种training loss正常吗?
> ![image](https://user-images.githubusercontent.com/548443/120994854-7ae98900-c7b7-11eb-8124-4d80ff57e6e9.png)

这个效果不正常，你训练配置有改吗？

**Comment by lonelydancer** [comment]
仿照pretrain/24L_train_stage-1.conf，我只修改了我的词表以及训练数据，batch_size,epoch_num

**Comment by sserdoubleh** [comment]
我用现在develop分支的代码重新测试训练，在4卡上的训练是正常的；我感觉可能是你对中文数据的处理上有问题？数据是怎么分词的，用的词表、分词工具是你自己的产生的吗？
之前你应该在plato-2上做过训练，有对develop分支的代码进行过更改吗？@lonelydancer

**Comment by lonelydancer** [comment]
词表是用sentencepiece工具生成的。
spm_train --input=dialog.train --model_prefix=med --vocab_size 8000 --character_coverage 0.9995  --shuffle_input_sentence=true --input_sentence_size=500000
我没有对代码做过修改。

**Comment by sserdoubleh** [comment]
> 词表是用sentencepiece工具生成的。
> spm_train --input=dialog.train --model_prefix=med --vocab_size 8000 --character_coverage 0.9995 --shuffle_input_sentence=true --input_sentence_size=500000
> 我没有对代码做过修改。

之前用plato-2分支训练是正常的吧？

**Comment by lonelydancer** [comment]
感觉也不正常。在连续几个step内有时候大有时候小。
你的意思是打印的loss在第一个epoch中，会持续的下降？
我的观察是一开始loss很大7.x，然后就很快降低到一个数值，然后上下抖动4.x,5.x。

**Comment by sserdoubleh** [comment]
用户修改lr到合适值，已经能够正常跑了，如果有问题，再open这个issue吧

**Comment by lonelydancer** [comment]
@sserdoubleh 感谢大力支持！

**Comment by sxmafei** [comment]
请问lr多少合适呢

**Comment by sserdoubleh** [comment]
> 请问lr多少合适呢


可以先参考论文的实验设置哦，具体设置跟模型规模是有关的 @sxmafei 
https://github.com/PaddlePaddle/Knover/tree/develop/projects/PLATO-2
