### ISSUE TITLE
关于vocab字典格式错误

### ISSUE THREAD

**Issue by guijuzhejiang** [PaddlePaddle/Knover#58]
我用sentencepiece生成了vocab字典，model type是unigram。字典中第二列不是index整数，而是float的概率，所以运行训练时报错：ValueError: invalid literal for int() with base 10:
代码位置是vocab[token] = int(index)
因为index是浮点数，所以转换失败。
请问这里我要改字典还是代码呢？

**Comment by guijuzhejiang** [comment]
vocab大概长这个样子：
、	-3.00936
。	-3.28261
▁	-3.52378

**Comment by guijuzhejiang** [comment]
暂时先把代码：index = items[1] if len(items) == 2 else num
改成：index = num
不知道这样会不会引起其他问题

**Comment by sserdoubleh** [comment]
我们现在提供的sentencepiece的model type是bpe，如果是unigram的话，有两种解决方案，一个是按你现在这种做法，改load_vocab（建议对一下，原始文本转成id，再根据修改后的词表映射回去，是不是完全一致的），另一种是直接改vocab.txt（也不会影响spm model的encodedecode，因为这个分词模型主要还是依赖.model文件）

**Comment by guijuzhejiang** [comment]
感谢回复，我先用第一种简单方式做。真是个不错的框架
