### ISSUE TITLE
AttributeError: 'Plato' object has no attribute 'args'

### ISSUE THREAD

**Issue by guijuzhejiang** [PaddlePaddle/Knover#59]
训练plato模型时报错：
File "/home/zzg/workspace/pycharm/Knover/knover/core/model.py", line 225, in load
    self.args.start_step = start_step[0]
AttributeError: 'Plato' object has no attribute 'args'
查看model.py代码如下：
        if is_checkpoint:
            print(f"Load model from checkpoint: {model_path}")
            start_step = get_tensor("@LR_DECAY_COUNTER@")
            if start_step is not None:
                self.args.start_step = start_step[0]
原因：初始化init时确实没有初始化args。
疑问：需要在init中加上self.args=args吗？感觉好像没用到self.args吧

**Comment by guijuzhejiang** [comment]
感觉把下面的代码删掉就行了吧。不过为什么其他人没遇到这个问题呢，都偷偷的改了吗？
start_step = get_tensor("@LR_DECAY_COUNTER@")
if start_step is not None:
self.args.start_step = start_step[0]

**Comment by sserdoubleh** [comment]
这里的args只是为了方便从checkpoint中获取已经训练多少个step，这里应该是我commit的时候忘了把这个修改加进去了，我改下

**Comment by guijuzhejiang** [comment]
谢谢，我关掉了
