### ISSUE TITLE
用NSP做infer的时候报错

### ISSUE THREAD

**Issue by guijuzhejiang** [PaddlePaddle/Knover#61]
按着文档做infer时报了下面的错误：
UnavailableError: Load operator fail to open file output/NSP/infer_model/encoder_layer_0_multi_head_att_key_fc.b_0, please check whether the model file is complete or damaged.
      [Hint: Expected static_cast<bool>(fin) == true, but received static_cast<bool>(fin):0 != true:1.] (at /paddle/paddle/fluid/operators/load_op.h:41)
      [operator < load > error]
是NSP模型有问题吗？

**Comment by guijuzhejiang** [comment]
通过save_inference_model.sh生成的NSP的__model__文件只有2.7M，请问这是正常的吗？

**Comment by guijuzhejiang** [comment]
我把提供的英语模型的NSP和Plato的两个模型也用save_inference_model.sh生成了对应__model__模型,也只有几M大。并且跑infer时也报了同样的错误：UnavailableError: Load operator fail to open file ./pretrained_model/PLATO-2/24L/NSP_infer_model/encoder_layer_0_multi_head_att_key_fc.b_0, please check whether the model file is complete or damaged.
怀疑是是不是我的save_inference_model.sh有问题？我贴出来,麻烦大佬帮我看一下，谢谢
#!/bin/bash
set -eux

python -m \
    knover.scripts.save_inference_model \
    --model NSPModel \
    --task NextSentencePrediction \
    --vocab_path "./package/dialog_en/vocab.txt" \
    --spm_model_file "./package/dialog_en/spm.model" \
    --init_checkpoint "./pretrained_model/PLATO-2/24L/NSP" \
    --inference_model_path "./pretrained_model/PLATO-2/24L/NSP_infer_model" \
    ${save_args:-} \
    --config_path "./package/dialog_en/24L.json"

**Comment by sserdoubleh** [comment]
有检查运行路径的相对路径 output/NSP/infer_model/encoder_layer_0_multi_head_att_key_fc.b_0 存在吗？
这个__model__的大小正常，这个文件只是保存模型的结构，不包含参数

**Comment by guijuzhejiang** [comment]
@sserdoubleh 谢谢回复。
output/NSP/infer_model只有一个__model__文件。没有其他文件了。
是不是要把__model__和init_checkpoint的路径统一啊，也就是把生成的__model__和checkpoint放一起是吗？

**Comment by guijuzhejiang** [comment]
果然是要放一起，inference_model_path和init_checkpoint写一个路径就可以了。大意了。感谢@sserdoubleh
