### ISSUE TITLE
多伦对话的max_src_len是不是要设置长一些？

### ISSUE THREAD

**Issue by guijuzhejiang** [PaddlePaddle/Knover#62]
我理解的max_src_len是包括了人设，历史信息，本轮对话的上一句，这三部分加和后的最大长度，max_tgt_len是本轮对话的下一句的最大长度，max_seq_len是max_src_len+max_tgt_len的最大长度，这样理解对吗？如果对的话是不是要把max_src_len设置的长一些？中文对话训练里一个文字是2个字节，所以我设置的max_src_len=1600，这样对训练有什么影响呢？

**Comment by sserdoubleh** [comment]
你要把model config的json文件中`max_position_embeddings`设置得更大一些
你是在重头pretrain还是在现有模型的基础上fine-tune？

**Comment by guijuzhejiang** [comment]
@sserdoubleh 谢谢。
我是重头训练自己的模型。我把四个参数都设置的更长了。下面这样修改对不？
stage-1.conf：
train_args="--max_src_len 1600 --max_tgt_len 320 --max_seq_len 1920 --is_cn true"
24L.json:
"max_position_embeddings": 1920,

**Comment by sserdoubleh** [comment]
这么改可以的
中文一个字占两个字节其实不重要，主要是这些len都是按token数算的

**Comment by guijuzhejiang** [comment]
谢谢，关闭。
