### ISSUE TITLE
训练代码中对角色信息是怎么处理的

### ISSUE THREAD

**Issue by guijuzhejiang** [PaddlePaddle/Knover#63]
百度的预训练模型很强大，推理时可以将角色放在上下文中做出响应。我想用自己的数据做加入自己设定的角色进行训练，参照了数据example/train.tsv中加入your persona:的做法，但查看代码dialog_reader.py中，里面并没有针对"your persona:"字段做特殊处理，请问百度训练时，对带有"your persona:"的信息是怎么处理的？

**Comment by guijuzhejiang** [comment]
会不会是把"your persona:"后面的内容提取出来，加到了knowledge_field_values里面进行训练？

**Comment by sserdoubleh** [comment]
需要用户自己在数据处理的时候，把知识相关的放到新增knowledge列上，knover现在是不会自动处理的
另外需要调整model config的json文件中的type_vocab_size，设置为3，后面会用type_id=2单独表示knowledge

至于样例数据中的”your persona:“前缀，是期望模型自己学习具备分辨knowledge的能力，也是另一种区分knowledge的方案

**Comment by guijuzhejiang** [comment]
@sserdoubleh 谢谢。我再确认三个问题。
1，人设信息和knowledge毕竟还不太一样，把人设放到knowledge列，能学出来合适的人设吗？
2，代码里加入knowledge时分了pre_src和post_src，放前面或者后面有什么区别吗？
3，如果不做knowledge列，用您说的第二个方案，在数据中加”your persona:“前缀，期望模型自己学习分辨knowledge的能力，这个效果怎么样？

**Comment by sserdoubleh** [comment]
1. 没明白人设信息和knowledge有啥不一样？这里只是用一个特定的type_id区分了人设、对话历史以及回复
2. 这主要是对齐不同的数据处理方式，可能会影响模型的效果
3. 这两个方案其实从实际使用的角度上看，效果不会差太多的，我在PersonaChat上做过实验，用type_id区分效果有好一点点

**Comment by guijuzhejiang** [comment]
@sserdoubleh 感谢分享你的经验。1说的人设是指人的性格，比如说我给出人设是中二男生，或者傲娇女王，后面模仿他们的口吻做成对话语料。希望模型学到特定性格d人物的说话方式。但我仔细想了一下，这和knowledge是完全不一样的，说话方式是根据所有训练语料学来的.这里的knowledge是基于内容的。
