### ISSUE TITLE
请问use_role参数是怎么用的

### ISSUE THREAD

**Issue by guijuzhejiang** [PaddlePaddle/Knover#64]
请问use_role参数是标记什么的？是对话中的A和B吗？要怎么使用呢？

**Comment by sserdoubleh** [comment]
在多人对话中，区分不同的角色
这个可以参考代码吧：https://github.com/PaddlePaddle/Knover/blob/154d3f2eb6468ba025f31e72ca1919f43074536d/knover/data/dialog_reader.py#L144
就是在每个 utterance的后面会接一个role_id

**Comment by guijuzhejiang** [comment]
@sserdoubleh 谢谢。代码看过了，主要是不确定数据的做法。
如果A，B，C三个人说话，数据是不是要做成下面这样？
src：你好\1A[SEP]你好\1B[SEP]你好\1C[SEP]...
tgt：你好

**Comment by sserdoubleh** [comment]
role_id 的设置目前有两个约束：
1. role_id 使用上从0开始，最多到 model config 里的`role_type_size - 1`
2. tgt 的 role_id 为0

我使用的时候往往是倒序编码role_id，从 tgt 开始往回逐一确认各个 utterance 的 role id，如果现在考虑的 utterance 是由一个新的角色说，就使用新的role_id，如果遇到之前编码过的角色，就使用对应的 role_id
像你上面那个例子：
src：你好 \1 1 [SEP] 你好 \1 0 [SEP] 你在做什么？\1 1
tgt：我在看电视 \1 0

**Comment by guijuzhejiang** [comment]
@sserdoubleh 非常感谢，介绍的很详细。目前的训练语料是没有标注对话人role_id的，但效果也很好，是模型自己学到了吧。可不可以理解为只有两个人的话，不需要标注role_id。三个人或以上需要标注role_id？还有，有这种多角色对话的开源数据集吗？

**Comment by sserdoubleh** [comment]
在两人对话的数据集上，模型能够很好地直接学习到角色的关系，增加 role embedding 也没有特别的提升

多角色对话的开源数据集，据我所知英文有一些（比如 opensubtitle），不过还需要做下数据处理

**Comment by guijuzhejiang** [comment]
@sserdoubleh 非常感谢你的耐心回答，问题关闭。
