### ISSUE TITLE
在预测中num_samples和topk的关系

### ISSUE THREAD

**Issue by guijuzhejiang** [PaddlePaddle/Knover#65]
我看文档里给出的预测参数里默认是--num_samples 20 --topk 5.不太理解num_samples和topk的关系。
topk5的话，是说按概率大小排序后，从前5个里面采样一个作为输出token。
那num_samples 20是做什么用的呢？

**Comment by sserdoubleh** [comment]
topk是设置 topk sampling 算法的超参，指每生成一个 token 的时候，是在概率前 k 大的 token上做 sampling
num_samples 是指做多次序列采样，采样20次，得到20个回复之后，取其中分数最高（默认length normalized PPL）的样本，作为最终的生成结果

**Comment by guijuzhejiang** [comment]
@sserdoubleh 谢谢，能具体说一下序列采样是怎么做的吗？

**Comment by sserdoubleh** [comment]
序列采样就是应用采样算法，如topk sampling，一个 token 一个 token 的做采样，直到采样到 EOS，完成一个序列（回复）的采样
因为采样具有随机性，所以可以采样多个不同的候选回复，后面可以再根据一些策略对候选回复进行排序

**Comment by guijuzhejiang** [comment]
@sserdoubleh 理解了，非常感谢，问题闭关。
