### ISSUE TITLE
Undefined name do_test

### ISSUE THREAD

**Issue by mateuszz0000** [PaddlePaddle/Knover#7]
Hello, 

In `dialog_reader` found followoing error:
`/Knover/readers/dialog_reader.py:374:73: F821 undefined name 'do_test'`

**Comment by sserdoubleh** [comment]
Thanks for report, we fix the bug and support training with filelist now.
You can find the related configuration in https://github.com/PaddlePaddle/Knover/blob/master/package/dialog_en/plato/24L_train.conf
