### ISSUE TITLE
关于paddle的docker image问题

### ISSUE THREAD

**Issue by CristianYuuKi** [PaddlePaddle/Knover#71]
下载paddle的2.1.0镜像创建容器后按照步骤install了所需要的包，再运行plato-2的interact的时候会报这个错误
![1](https://user-images.githubusercontent.com/26245903/129464276-494433e0-4181-4328-baff-addf87bad646.png)
![2](https://user-images.githubusercontent.com/26245903/129464278-d2e9fdd9-b85e-46ae-a5e5-deae2696c533.png)

源代码只在interaction.py中添加了
"import paddle
paddle.enable_static()"
这俩行代码

想知道可能的原因是什么

**Comment by sserdoubleh** [comment]
plato-2分支的代码还是基于paddle1.8开发的，如果使用paddle2.0之后的版本，可以转用develop分支的代码

**Comment by ARCHERZJT** [comment]
> plato-2分支的代码还是基于paddle1.8开发的，如果使用paddle2.0之后的版本，可以转用develop分支的代码

但是我下载完Knover后，cd Knover就进入MASTER模式了，怎么切换成develop模式，求教，谢谢

**Comment by CristianYuuKi** [comment]
> plato-2分支的代码还是基于paddle1.8开发的，如果使用paddle2.0之后的版本，可以转用develop分支的代码

走develop模式下没改动代码，出现这个问题
![11](https://user-images.githubusercontent.com/26245903/129542455-c29e5cce-da7d-453a-b651-5178b5cc2f54.png)

**Comment by sserdoubleh** [comment]
模型是从develop分支下载的吗？

**Comment by ARCHERZJT** [comment]
> 模型是从develop分支下载的吗？

**Comment by CristianYuuKi** [comment]
> 模型是从develop分支下载的吗？

解决啦，看到底下有人问了同样的问题，删掉了__model__后能正常运行了，谢谢
