### ISSUE TITLE
Incorrect arguments in bash scripts

### ISSUE THREAD

**Issue by Evraa** [PaddlePaddle/Knover#74]
This line in projects/Plato-2/README.md:

bash ./scripts/local/job.sh ./project/PLATO-2/pretrain/24L_inference.conf

should be:

bash ./scripts/local/job.sh **./projecst/PLATO-2/pretrain/24L_infer.conf**

Same for all similar lines...

**Comment by sserdoubleh** [comment]
I will fix this soon. Thx for feedback.
