### ISSUE TITLE
关于使用finetune Knover进行infer时，同一个语料库的infer结果每次都不一样

### ISSUE THREAD

**Issue by xcluo** [PaddlePaddle/Knover#77]
你好，我使用自己的数据对Knover Classfier进行finetune后保存checkpoint （我们发现保存的checkpoint有2612个参数文件比提供的[SOP-32L-Context](https://dialogue.bj.bcebos.com/Knover/projects/DSTC9-Track1/SOP-32L-Context.tar)模型的522个多了近4倍），然后基于这个checkpoint使用infer.sh进行预测，但是同一个数据集的预测结果每次都不一致，请问这种情况正常么？该如何解决？

**Comment by xcluo** [comment]
@sserdoubleh

**Comment by sserdoubleh** [comment]
1. 保存的 checkpoint 文件包含了 optimizer state（如Adam 的 moment1，moment2）这些，是会比我们单纯提供参数的文件数更多
2. 每次预测不一致，这点不是很正常，用 repo 里提供的 checkpoint 会出现预测结果不一致的情况吗？

**Comment by luomou97** [comment]
1. 确实相较于repo中release的参数是关于optimizer的，如moment，beta等。理论上这些多出来的参数不影响infer阶段对吧？
2. 使用repo中的checkpoint每次预测结果都一致，在infer时只简单地改变init_params=<our_finetuned_model>就会出现预测结果不一致的问题

**Comment by xcluo** [comment]
1. 确实相较于repo中提供的checkpoint多出来的参数是关于optimizer的，如moment，beta等。理论上这些多出来的参数不影响infer阶段对吧？
2. 使用repo中的checkpoint每次预测结果都一致，**在infer时只简单地改变init_params=<our_finetuned_model>**就会出现预测结果不一致的问题

**Comment by sserdoubleh** [comment]
1. 这些不会影响输出
2. 可以对比下使用你的finetune模型，两次跑的结果的 inference_output.txt 是否一致先？

**Comment by xcluo** [comment]
最终比较溯源发现某些细节参数设置错了，自己的原因，感谢解惑，knover功能确实强大👍
