### ISSUE TITLE
infer的时候latent_id为什么指定为0，这个ID怎么发挥引导回复多样性的作用

### ISSUE THREAD

**Issue by jidlin** [PaddlePaddle/Knover#80]
如题，测试的时候发现latent_id是指定为0的，所以在使用的时候是需要人工指定latent_id吗，怎么确定每一步使用什么ID

**Comment by sserdoubleh** [comment]
https://github.com/PaddlePaddle/Knover/blob/ac58d760973cacb163b5dc5e1be0b7c54ca75140/knover/models/plato.py#L295
data_reader 里面只是为了匹配 data_loader 的输入格式，实际使用的就是 num_latent 个 latent 进行预测
