### ISSUE TITLE
运行bash ./scripts/local/job.sh ./project/PLATO-2/pretrain/24L_inference.conf该命令时出现Exception: 'feed_targets' does not have label_pos variable

### ISSUE THREAD

**Issue by lichade-son** [PaddlePaddle/Knover#85]
运行bash ./scripts/local/job.sh ./project/PLATO-2/pretrain/24L_inference.conf该命令时出现异常：
![image](https://user-images.githubusercontent.com/65451118/135756271-d789f090-b455-42dd-886e-d4d092397967.png)
进入到inference_utils.py文件中查看__predict__函数里面打印了inputs发现里面确实没有label_pos但是有一个label_idx不知道是不是改变量名了？

**Comment by sserdoubleh** [comment]
你用的可能是旧的模型链接，只需要把模型目录下的__model__删了，让脚本重新生成即可，或者你从最新的链接下载新的模型
