### ISSUE TITLE
推理模型的文件大小

### ISSUE THREAD

**Issue by guijuzhejiang** [PaddlePaddle/Knover#90]
对比了你提供的预训练模型和自己生成的训练模型，发现自己生成的模型有4.1G，比你的大很多，多了一些文件，请问推理时是否要把带有'_beta1_pow_acc_0','_beta2_pow_acc_0','_moment1_0','_moment2_0'这四个后缀的文件从模型文件中删除？

**Comment by sserdoubleh** [comment]
可以删除，推理的时候用不到

**Comment by guijuzhejiang** [comment]
谢谢回复
