### ISSUE TITLE
lantent参数对推理的影响

### ISSUE THREAD

**Issue by guijuzhejiang** [PaddlePaddle/Knover#93]
请问latent参数的大小对产生对话的具体影响是什么。现在用的默认值20，如果改成50的话，会怎么样？

**Comment by sserdoubleh** [comment]
latent 的数量主要影响生成的多样性，但是随着 latent 数量增大，训练难度增加（latent 的表示学习比较困难）

**Comment by guijuzhejiang** [comment]
谢谢回复
